version: '3.8'

services:
  app:
    container_name: "code_dungeons_app"
    build: "./"
    command: "streamlit run main.py --server.port=8501 --server.address=0.0.0.0"
    ports:
      - ${HOST_PORT}:8501
    env_file:
      - .env
    volumes:
      - ./:/src/
  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./ollama:/root/.ollama